[profile.default]
src = 'contracts'
test = 'test/foundry/'
libs = ["lib"]
solc_version = "0.8.20"
ignored_error_codes = [5159] # selfdestruct in contracts/mocks/SuperfluidDestructorMock.sol
# deny_warnings = true
# keep in sync with truffle-config.js
evm_version = 'paris'
remappings = [
    '@ethereum-contracts/contracts/=contracts/',
    '@oz_superfluid/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
out = 'build/foundry/default'

[invariant]
runs = 2000
depth = 10
fail_on_revert = false

[fmt]
bracket_spacing = true
tab_width = 4
line_length = 120
int_types = "preserve"
quote_style = "double"
wrap_comments = true

[profile.ci]
offline = true

[profile.ci.fuzz]
runs = 1000
